name: Build and Push Docker Image

on:
  workflow_dispatch:  # 手动触发
  push:
    branches:
      - main

env:
  TORCH_VERSION: "2.9.0"      # PyTorch 版本号
  CUDA_VERSION: "12.8.1"      # CUDA 版本号
  UBUNTU_VERSION: "24.04"     # Ubuntu 版本号
  PYTHON_VERSION: "3.12.10"   # Python 版本号

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Define image tag
        id: tag
        run: |
          IMAGE_TAG=torch${{ env.TORCH_VERSION }}-cu${{ env.CUDA_VERSION }}-cudnn-ubuntu${{ env.UBUNTU_VERSION }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build --no-cache \
            --build-arg TORCH_VERSION=${{ env.TORCH_VERSION }} \
            --build-arg CUDA_VERSION=${{ env.CUDA_VERSION }} \
            --build-arg UBUNTU_VERSION=${{ env.UBUNTU_VERSION }} \
            --build-arg PYTHON_VERSION=${{ env.PYTHON_VERSION }} \
            -t ${{ secrets.DOCKER_USERNAME }}/torch-cuda-runtime:${{ steps.tag.outputs.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/torch-cuda-runtime:${{ steps.tag.outputs.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/torch-cuda-runtime:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/torch-cuda-runtime:${{ steps.tag.outputs.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/torch-cuda-runtime:latest
